demo1/attractionApp/urls.py
from django.contrib.auth import views as authView
from django.urls import path
from .import views

app_name = 'attractionApp'

urlpatterns = [ 
    path('createAttraction/',views.createAttraction,name="createAttraction"),
    path('geocoding/',views.geocoding,name='geocoding') ,
]

demo1/demo1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('', include('demo_app.urls', namespace="demo_app")),
    path('', include('user.urls', namespace="user")),
    path('admin/', admin.site.urls),
    path('',include('attractionApp.urls',namespace="attraction")),
    path('',include('routeApp.urls',namespace="routeApp")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

demo1/demo_app/urls.py
from django.urls import path
from .import views

app_name = 'demo_app'

urlpatterns = [

    path('', views.index, name='index'),
    path('home/', views.home, name='home'),
    path('map/',views.map,name='map'),
    
]

demo1/routeApp/urls.py
from unicodedata import name
from django.urls import path
from .import views

app_name = 'routeApp'

urlpatterns = [
    path('createRoute/',views.createRoute,name="createRoute"),
    path('createDayRoute/id=<bigRoute_id>',views.createDayRoute,name="createDayRoute"),
    path('dayRouteTem/dayRouteId=<dayRoute_id>',views.dayRouteDetail,name="dayRouteDetail"),
    path('addCity/',views.addCity,name="addCityMethod"),
    path('addAttraction/',views.addAttraction2,name="addAttractionMethod"),
    path('everyDayMap/',views.everyDayMap,name='everyDayMap'),
]

demo1/user/urls.py
from django.contrib.auth import views as authView
from django.urls import path
from .import views

app_name = 'user'

urlpatterns = [ 
    path('signup/', views.signupUser, name='signup'),
    path('login/', views.loginUser, name ='login'),
    path('logout/',  views.logoutUser, name ='logout'),
    path('userinformation/',views.userinformation,name ='userinformation')
]

demo1/templates/addCity.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
home page
{% endblock %}

{% block body_block %}
<style>
    .form {
        width: 700px;
        box-shadow: 0 0 3px 0 rgb(0, 0, 0, 0.3);
        background: white;
        padding: 20px;
        margin: 3% auto 0;
    }

    .returnA {
        color: #000000;
        padding: 4px;
        text-decoration: none;
        font-size: 15px;
        background-color: #dce1e6;
        float: left;

    }
</style>
{% csrf_token %}
<link rel="stylesheet" href="{% static 'plugins/bootstrap/signup.css' %}">
<div class="form">
    <div>
        <h3 style="text-align: center;">
            Add City Please
        </h3>
        <input type="hidden" id="dayRoute_Id" value="{{dayRouteObject.dayRouteId}}">

        Your preferred city location for this trip:
        {% for i in recommendRegion %}
        {{i.regionName}},
        {% endfor %}

        </br>

        Depending on your preference, recommended cities:
        </br>
        {% for i in recommendCity %}

        <input name="city" id="{{i.cityId}}" type="checkbox" value="{{ i.cityId }}"> {{i.cityName}} ({{i.cityLikes}})
        </br>
        {% endfor%}
        </br>
        
        In addition to the above cities, other cities are also ranked high in the UK:
        </br>
        {% for i in otherCity %}

        <input name="city" id="{{i.cityId}}" type="checkbox" value="{{ i.cityId }}"> {{i.cityName}} ({{i.cityLikes}})
        </br>

        {% endfor %}

        <a class="returnA" href="{% url 'routeApp:dayRouteDetail' dayRouteObject.dayRouteId %}">
            Return
        </a>


        <button type="submit" id="submit" onclick="addCity()" style="float: right;">Add</button>
        <br />



    </div>
</div>


<script language="JavaScript">

    function addCity() {
        console.log("hi")
        var radio = document.getElementsByName("city");
        console.log(radio)
        var post_data = new Array();
        var number = 0;
        for (var n = 0; n < radio.length; n++) {
            // 挑选出被选的单位
            if (radio[n].checked == true) {
                //console.log(radio[n]);
                //console.log(radio[n].value)
                post_data.push(radio[n].id);
                number++
            }
        }

        var dayRoute_Id = document.getElementById("dayRoute_Id").value
        console.log(dayRoute_Id)
        //console.log("giao.........////")

        //console.log(title);
        //console.log(days);
        all_data = {
            'dayRoute_Id': dayRoute_Id,
            'city': post_data,

        }


        $.ajax({
            type: "POST",
            url: "/addCity/",
            data: JSON.stringify(all_data),
            // data: {
            //     'post_data':post_data
            // },
            //---------giao----------
            dataType: 'json',
            //---------giao----------

            success: function (data) {
                window.location = data.msg

                console.log('giaogggggg');
            }
        })

    }
</script>
{% endblock %}

demo1/templates/addatt.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
home page
{% endblock %}

{% block body_block %}
<style>
    .form {
        width: 700px;
        box-shadow: 0 0 3px 0 rgb(0, 0, 0, 0.3);
        background: white;
        padding: 20px;
        margin: 3% auto 0;
    }

    .returnA {
        color: #000000;
        padding: 4px;
        text-decoration: none;
        font-size: 15px;
        background-color: #dce1e6;
        float: left;
    }

    .form1 {
        width: 700px;
        box-shadow: 0 0 3px 0 rgb(0, 0, 0, 0.3);
        background: white;
        padding: 20px;
        margin: 1% auto 0;
    }
</style>
{% csrf_token %}
<div class="form">
    <div class="sen">
        <h3 style="text-align: center;">
            Add Attraction Please
        </h3>

        <input type="hidden" id="dayRoute_Id" value="{{dayRouteObject.dayRouteId}}">

        The type of attractions you enjoyed more on this trip:
        {% for i in recommendCategory %}

        {{i.categoryName}},
        {% endfor %}

        </br>

        The city you are going to today is:
        {% for i in todayCity %}
        {% if i.cityName %}
        {{ i.cityName }},
        {% else %}
        {{i}}
        {% endif %}
        {% endfor %}

        </br>
        </br>

        Depending on your preferences, the recommended attractions:
        </br>
        {% for i in allAttractionResult %}
        <input name="attraction" id="{{i.attractionId}}" type="checkbox" value="{{ i.attractionId }}">
        {{i.attractionName}} ({{i.attractionLikes}})</br>

        {% endfor %}

        </br>
        </br>

        There are other famous attractions of this city:
        </br>
        {% for i in excludeReList %}

        <input name="attraction" id="{{i.attractionId}}" type="checkbox" value="{{ i.attractionId }}">
        {{i.attractionName}} ({{i.attractionLikes}})</br>

        {% endfor %}



        <a class="returnA" href="{% url 'routeApp:dayRouteDetail' dayRouteObject.dayRouteId %}">
            Return
        </a>

        <div>
            <button type="submit" id="submit" onclick="addAttraction()" style="float: right;">Add</button>
            <br />
        </div>

    </div>
</div>

<script language="JavaScript">

    function addAttraction() {
        console.log("hi")
        var radio = document.getElementsByName("attraction");
        console.log(radio)
        var post_data = new Array();
        var number = 0;
        for (var n = 0; n < radio.length; n++) {
            // 挑选出被选的单位
            if (radio[n].checked == true) {
                //console.log(radio[n]);
                //console.log(radio[n].value)
                post_data.push(radio[n].id);
                number++
            }
        }

        var dayRoute_Id = document.getElementById("dayRoute_Id").value
        console.log(dayRoute_Id)
        //console.log("giao.........////")

        //console.log(title);
        //console.log(days);
        all_data = {
            'dayRoute_Id': dayRoute_Id,
            'attraction': post_data,

        }


        $.ajax({
            type: "POST",
            url: "/addAttraction/",
            data: JSON.stringify(all_data),
            // data: {
            //     'post_data':post_data
            // },
            //---------giao----------
            dataType: 'json',
            //---------giao----------

            success: function (data) {
                window.location = data.msg

                console.log('giaogggggg');
            }
        })

    }
</script>


{% endblock %}

demo1/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
<!-- 页头信息 -->

<head>
    <meta charset="utf-8">
    <title>
        {% block title%}
        base page
        {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'plugins/bootstrap/bootstrap.min.css' %}">

    <link rel="stylesheet" href="{% static 'plugins/fontawesome/css/all.min.css' %}">

    <link rel="stylesheet" href="{% static 'plugins/slick/slick.css' %}">
    <link rel="stylesheet" href="{%static 'plugins/slick/slick-theme.css' %}">

    <link rel="stylesheet" href="{% static '/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-5.2.0-dist' %}">

    <header class="navigation">
        <div id="navbar">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <nav class="navbar navbar-expand-lg px-0 py-4">
                            <a class="navbar-brand" href="{% url 'demo_app:home' %}">Yongsen</a>
                            <button class="navbar-toggler collapsed" type="button" data-toggle="collapse"
                                data-target="#navbarsExample09" aria-controls="navbarsExample09" aria-expanded="false"
                                aria-label="Toggle navigation">
                            </button>

                            <div class="collapse navbar-collapse text-center" id="navbarsExample09">
                                <ul class="navbar-nav ml-auto">
                                    <div class="my-2 my-md-0 ml-lg-4 text-center">
                                        <a href="#" class="btn btn-solid-border btn-round-full">Communication
                                            platform</a>
                                    </div>
                                    <div class="my-2 my-md-0 ml-lg-4 text-center">
                                        <a href="{% url 'routeApp:createRoute'%}" class="btn btn-solid-border btn-round-full">Create plan</a>
                                    </div>
                                    {% if request.user.is_authenticated %}
                                    <div class="my-2 my-md-0 ml-lg-4 text-center">
                                        <a href="{% url 'attractionApp:geocoding' %}"
                                            class="btn btn-solid-border btn-round-full">Search attraction</a>
                                    </div>
                                    <div class="my-2 my-md-0 ml-lg-4 text-center">
                                        <a class="btn btn-solid-border btn-round-full" href="{% url 'user:userinformation'%}"> Welcome: {{request.user.username }}</a>
                                    </div>

                                    <div class="my-2 my-md-0 ml-lg-4 text-center">
                                        <a href="{% url 'user:logout' %}"
                                            class="btn btn-solid-border btn-round-full">Logout</a>
                                    </div>


                                    {% else %}
                                    <div class="my-2 my-md-0 ml-lg-4 text-center">
                                        <a href="{% url 'user:login' %}"
                                            class="btn btn-solid-border btn-round-full">Login</a>
                                    </div>
                                    <div class="my-2 my-md-0 ml-lg-4 text-center">
                                        <a href="{% url 'user:signup' %}"
                                            class="btn btn-solid-border btn-round-full">Register</a>
                                    </div>
                                    {% endif %}

                                </ul>
                            </div>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </header>
</head>


<body>
    <script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'plugins/bootstrap/bootstrap.min.js' %}"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU" defer></script>
    <script src="{% static 'plugins/google-map/map.js' %}" defer></script>
    <div>
        {% block body_block %}
        
        {% endblock %}
    </div>

 

</body>
<!-- <footer class="footer">
    <div class="footer-btm pt-4">
        <div class="row">
            <div class="col-lg-6">
                <div class="copyright">
                    Here is my GitHub:
                    <br /><a href="https://github.com/Yongsenluo">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Yongsen</a>
                </div>
            </div>
        </div>
    </div>

</footer> -->



</html>

demo1/templates/createAttraction.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    home page
{% endblock %}

{% block body_block %}
<div>
    this is create attraction/city html
</div>

{% endblock %}

demo1/templates/createDayRoute.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
home page
{% endblock %}

{% block body_block %}
{% csrf_token %}
<script src="{% static '/plugins/jquery/jquery.min.js' %}"></script>
<script src="{% static '/plugins/bootstrap-5.2.0-dist/js/bootstrap.js' %}"></script>
<link rel="stylesheet" href="{% static '/css/createDayRoute.css' %}">

<div class="content">
    <!--左侧导航栏-->
    <div class="content-left">
        <div class="left-title">
            <div class="routeInformation">
                Route Titile: {{ bigRouteObject.routeName }}<br />
                Route User: {{ bigRouteObject.routeUser.username }}<br />
                Route Create Date: {{ bigRouteObject.routeDate }}<br />
                Route Likes: {{bigRouteObject.routeLike}}<br />
                Route Comments: {{bigRouteObject.routeComment}}<br />
            </div>
        </div>
        <!--水平线-->
        <!-- <div class="seg"></div> -->

        <!-- {% for i in allDayRouteObjecs %}
        <div class="nav">
            <div class="nav-title123">
                <a id={{i.dayRouteId}} name="dayRouteId" href="{% url 'routeApp:dayRouteDetail' i.dayRouteId %}" style="color: white; ">
                    Day {{ i.dayRouteNumber }}
                </a>
            </div>
        </div>
        <div class="seg"></div>
        {% endfor %} -->


        <!--右侧内容区-->

    </div>
    <div class="content-right" style="background-color: white;">
        {% for i in allDayRouteObjecs %}
        <div class="nav">
            <div class="nav-title123" style="color: black;">
                <a id={{i.dayRouteId}} name="dayRouteId" href="{% url 'routeApp:dayRouteDetail' i.dayRouteId %}" style="color: black; font-size: medium; ">
                    Day {{ i.dayRouteNumber }}
                </a>
            </div>
        </div>
        <div class="seg"></div>
        {% endfor %}

    </div>
</div>

<script language="JavaScript">
    // var href = $('#a-link').attr('href');
    // $('#a-link').attr('href',href + $("#paymoney").text());

    // $(".nav-title123>a").each(function () {

    //     $(this).click(
    //         function (data) {
    //             //动态获取点击的id
    //             var dayRouteId = data.target.id;
    //                     $(".content-right").html($(this).html());
    //                     console.log('giaogggggg');
    //                 }
    //     )
    // })
</script>




{% endblock %}

demo1/templates/dayRouteTem.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
home page
{% endblock %}

{% block body_block %}
<style>
    .form {
        width: 700px;
        box-shadow: 0 0 3px 0 rgb(0, 0, 0, 0.3);
        background: white;
        padding: 20px;
        margin: 3% auto 0;
    }

    .button {
        display: inline-block;
        padding: 2px 6px;
        font-size: 3px;
        cursor: pointer;
        text-align: center;
        text-decoration: none;
        outline: none;
        color: #fff;
        background-color: #4CAF50;
        border: none;
        border-radius: 15px;
        box-shadow: 0 5px #999;
    }

    .button:hover {
        background-color: #3e8e41
    }

    .button:active {
        background-color: #3e8e41;
        box-shadow: 0 5px #666;
        transform: translateY(4px);
    }

    .returnA {
        color: #000000;
        padding: 4px;
        text-decoration: none;
        font-size: 15px;
        background-color: #dce1e6;
        float: right;

    }

    .form-1 {
        width: 700px;
        background: white;
        margin: 8% auto 0;
    }
</style>
{% csrf_token %}
<link rel="stylesheet" href="{% static 'plugins/bootstrap/signup.css' %}">
<div class="form">
    <h3 style="text-align: center;">
        Day {{dayRouteObject.dayRouteNumber}} Itinerary
    </h3>
    <div>
        Day Route Id: {{dayRouteObject.dayRouteId}}
    </div>
    <div>
        Today City:
        {% for i in dayRouteCity %}
        <div>
            <form method="POST">
                {{i.cityName}}
                ({{i.cityLikes}}),
                <button id="{{i.cityId}}" type="submit" class="button" name="delete_button_city"
                    value="{{i.cityId}}"> Delete</button>
            </form>
        </div>
        {% endfor %}
    </div>
    <div>
        {% for i in dayRouteAttraction %}
        <div>
            <form method="POST">
                Attraction name: {{i.attractionName}}
                Hots: {{i.attractionLikes}}
                <button id="{{i.attractionId}}" type="submit" class="button" name="delete_button"
                    value="{{i.attractionId}}"> Delete</button>
            </form>
        </div>


        {% endfor %}

    </div>


</div>
<div class="form-1">
    <form method="POST">
        <button class="returnA" value='add' name="addCity" style="float: left;">
            Add City
        </button>
        <button class="returnA" value='add' name="addAttraction" style="float: left;">
            Add Attractions
        </button>
        <button class="returnA" value='add' name="map" style="float: left;">
            Map
        </button>
    </form>

    <a class="returnA" href="{% url 'routeApp:createDayRoute' dayRouteObject.dayRoutetoBigRoute.routeId %}">
        Return
    </a>

</div>



{% endblock %}

demo1/templates/everyDayMap.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
everyday map
{% endblock %}

{% block body_block %}
<style>
    .form {
        width: autho;
        box-shadow: 0 0 3px 0 rgb(0, 0, 0, 0.3);
        background: white;
        padding: 20px;
        margin: 3% auto 0;
    }

    .returnA {
        color: #000000;
        padding: 4px;
        text-decoration: none;
        font-size: 15px;
        background-color: #dce1e6;
        float: right;

    }
</style>
<link rel="stylesheet" href="{% static '/css/googleMap.css' %}">
{% csrf_token %}
<div class="form">
    <div style="text-align:center">

        <body onload="initialize()">
            <div id="map" style="width: 1300px; height: 600px;">
            </div>

            <h4>
                Marker in the map is the places we need to go today
            </h4>

            {% for i in dir %}
            <input type="hidden" id="{{i.atttractionId}}" name="lat" value="{{i.attractionLat}}">
            Place Name: {{i.attractionName}}</br>

            <input type="hidden" id="{{i.atttractionId}}" name="lng" value="{{i.attractionLng}}">

            {% endfor %}

            <div>
                --------------------------------------------
            </div>
            <div>
                <a class="returnA" href="{% url 'routeApp:dayRouteDetail' dayRouteObject.dayRouteId %}">
                    Return
                </a>
            </div>
    </div>
</div>
<script
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDzgKg6zPvAkeEVugOuHFJf7VNRx5VvZW4&callback=initMap&v=weekly&language=en"
    defer></script>
<script>
    var geocoder;
    var map;


    function initialize() {
        geocoder = new google.maps.Geocoder();
        var latObjects = document.getElementsByName("lat")
        var lngObjects = document.getElementsByName("lng")

        var latlng = new google.maps.LatLng(Number(latObjects[0].value), Number(lngObjects[0].value));
        var mapOptions = {
            zoom: 13,
            center: latlng
        }

        map = new google.maps.Map(document.getElementById('map'), mapOptions);

        var latObjects = document.getElementsByName("lat")
        var lngObjects = document.getElementsByName("lng")
        console.log(latObjects)
        for (var n = 0; n < latObjects.length; n++) {
            lat = latObjects[n].value
            lng = lngObjects[n].value
            //console.log(lat)
            // 转number 类型
            lat = Number(lat)
            lng = Number(lng)
            //console.log(lat)
            var positions = new google.maps.LatLng(lat, lng);
            var marker = new google.maps.Marker({
                map: map,
                position: positions
            });
        }

    }
</script>

<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<!-- <script>
            $("#submit").click(function () {
                    $.ajax({
                        url: '',
                        type: 'POST',
                        data: {
                            address: $('#address').val()
                        },
                        success: function(data){
                            console.log(data)
                        }
                    })
                })
        </script>  -->


{% endblock %}

demo1/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    home page
{% endblock %}

{% block body_block %}
<section class="slider">
    <div class="container">
        <div class="row">
            <div class="col-lg-9 col-md-10">
                <div class="block">
                    <h1 class="animated fadeInUp mb-5">Create your travel plan now !</h1>
                    <a href="{% url 'routeApp:createRoute' %}" class="btn btn-main animated fadeInUp btn-round-full" aria-label="Get started">Get
                        started<i class="btn-icon fa fa-angle-right ml-2"></i></a>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

demo1/templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
login page
{% endblock %}

{% block body_block %}
<link rel="stylesheet" href="{% static 'plugins/bootstrap/signup.css' %}">
<div class="signup_form">
    <H1>Login Here!</H1>
    <form method="post" action="/login/">
        {% csrf_token %}
        <input type="name" class="input-box" placeholder="Your email" name="username">
        <small>Please input your username </small>
        <input type="password" class="input-box" placeholder="Your password" name="password">
        <button type="submit" class="btn btn-primary btn-sm">Login Now</button>
    </form>

    <!-- will show the messages (this messages write in view.sign()) -->
    {% for message in messages %}
        <p id="message"> {{message}}</p>
    {% endfor %}
    <div class="card-footer text-muted text-center">
        New User? <a href="{% url 'user:signup' %}">Sign up</a>
        <div class="text-center py-2">
            <small>
                <a href="#" class="text-muted">Forgot your password?</a>
            </small>
        </div>
    </div>




</div>


{% endblock %}

demo1/templates/signup.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
signup page
{% endblock %}

{% block body_block %}
<link rel="stylesheet" href="{% static 'plugins/bootstrap/signup.css' %}">



<div class="signup_form">
    <H1>Create an Account Here!</H1>
    <form action="" method="POST">
        {% csrf_token %}
        {% for filed in form %}
        <div class="filed">
            {{filed.label}} :
            <div>
                {{filed}}
            </div>
        </div>
       
        {% endfor %}
        <button type="submit" class="btn btn-primary">Create an Account</button>
       <!--  <input type="name" class="input-box" placeholder="Your name" name="username">
        <input type="email" class="input-box" placeholder="Your email" name="email">
        <small>Please input your email</small>
        <input type="password" class="input-box" placeholder="Your password" name="password1">
        <small>The password must contain letters, numbers, or special characters</small>
        <input type="password" class="input-box" placeholder="Confirm your password" name="password2">
        <button type="submit" class="btn btn-primary">Create an Account</button> -->
    </form>
        {{form.errors}}
    <div class="card-footer text-muted text-center">
        Already have an account?
        <div>
            <a href="{% url 'user:login' %}">Log in</a>
        </div>
    </div>

</div>


{% endblock %}

demo1/templates/testMap.html
<!DOCTYPE html>
{% load static %}

<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <link rel="stylesheet" href="{% static '/css/googleMap.css' %}">
    {% csrf_token %}

    <body onload="initialize()">
        <div id="map" style="width: 1300px; height: 600px;">
        
        
        
        </div>
        
        <input type="button" value="Search" onclick="codeAddress()">
        <a class="return" href="{% url 'demo_app:home' %}">
            Return
        </a>
        <form method="post">
            <input type="text" name="address" id="address">
            <button type="submit" id="submit">add</button>
        </form>
        {% for i in latlng %}
        {% endfor %}
        <div id="lat">{{ LatLng }}</div>

        <!-- <div>
            <form method="post">
                <input id="address" type="textbox" value="Sydney, NSW">
                <input type="button" value="Encode" onclick="codeAddress()">
            </form>
        </div> -->

        <script
            src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDzgKg6zPvAkeEVugOuHFJf7VNRx5VvZW4&callback=initMap&v=weekly&language=en"
            defer></script>
        <script>
            var geocoder;
            var map;
            function initialize() {
                geocoder = new google.maps.Geocoder();
                var latlng = new google.maps.LatLng(51.5072178, -0.1275862);
                var mapOptions = {
                    zoom: 11,
                    center: latlng
                }
                
                map = new google.maps.Map(document.getElementById('map'), mapOptions);
                var marker = new google.maps.Marker({
                        map: map,
                        position: latlng
                });
            }

            function codeAddress() {
                var address = document.getElementById('address').value;
                geocoder.geocode({ 'address': address }, function (results, status) {
                    var lat = results[0].geometry.location.lat();
                    
                    if (status == 'OK') {
                        map.setCenter(results[0].geometry.location);
                        var marker = new google.maps.Marker({
                            map: map,
                            position: results[0].geometry.location
                        });
                        console.log(results[0].geometry.location)
                    } else {
                        alert('Geocode was not successful for the following reason: ' + status);
                    }
                });
            }
        </script>

        <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
        <!-- <script>
            $("#submit").click(function () {
                    $.ajax({
                        url: '',
                        type: 'POST',
                        data: {
                            address: $('#address').val()
                        },
                        success: function(data){
                            console.log(data)
                        }
                    })
                })
        </script>  -->
    </body>

    


</body>


</html>

demo1/templates/userinformation.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
login page
{% endblock %}

{% block body_block %}
<link rel="stylesheet" href="{% static 'plugins/bootstrap/signup.css' %}">
<div class="signup_form">
    <h6>Here are the trips you have posted before</h6> 

    {% for i in route %}
    <div>
        <a href="{% url 'routeApp:createDayRoute' i.routeId %}">
            Route Title : {{i.routeName}};&emsp;  Time: {{i.routeDate}}
        </a>
    </div>
    {% endfor %}
</div>


{% endblock %}